// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebVendasMVC.Data;

namespace WebVendasMVC.Migrations
{
    [DbContext(typeof(WebVendasMVCContext))]
    [Migration("20220601052234_AddEntidades")]
    partial class AddEntidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebVendasMVC.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("WebVendasMVC.Models.Vendas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data_Venda");

                    b.Property<int>("Status");

                    b.Property<double>("ValVendas");

                    b.Property<int?>("VenderoresId");

                    b.HasKey("ID");

                    b.HasIndex("VenderoresId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("WebVendasMVC.Models.Venderores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DepartmentId");

                    b.Property<DateTime>("Dt_aniversario");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<double>("SalarioBase");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Venderores");
                });

            modelBuilder.Entity("WebVendasMVC.Models.Vendas", b =>
                {
                    b.HasOne("WebVendasMVC.Models.Venderores", "Venderores")
                        .WithMany("listaVendas")
                        .HasForeignKey("VenderoresId");
                });

            modelBuilder.Entity("WebVendasMVC.Models.Venderores", b =>
                {
                    b.HasOne("WebVendasMVC.Models.Department", "Department")
                        .WithMany("venderores")
                        .HasForeignKey("DepartmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
